//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Practice_4.Model.DB.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jatin_dEntities2 : DbContext
    {
        public Jatin_dEntities2()
            : base("name=Jatin_dEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login_page> Login_page { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<User_login> User_login { get; set; }
    }
}
