//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanjayTest.Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SP355_SanjayMvcTestEntities : DbContext
    {
        public SP355_SanjayMvcTestEntities()
            : base("name=SP355_SanjayMvcTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    
        public virtual ObjectResult<SP_GetQuestionsAndAnswers_Result> SP_GetQuestionsAndAnswers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetQuestionsAndAnswers_Result>("SP_GetQuestionsAndAnswers");
        }
    }
}
