//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandeepMVC3_Test.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.City = new HashSet<City>();
            this.Registration = new HashSet<Registration>();
        }
    
        public int id { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Cid { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Registration> Registration { get; set; }
    }
}
