//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoupenCodeMaster
    {
        public int CoupenId { get; set; }
        public string Code { get; set; }
        public bool Type { get; set; }
        public Nullable<int> FlatAmount { get; set; }
        public Nullable<int> PercentageAmount { get; set; }
        public System.DateTime Expiry { get; set; }
        public int Limit { get; set; }
        public bool IsActive { get; set; }
    }
}
