//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagination_Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int? UserTypedid { get; set; }
        public string Address { get; set; }
        public int MobileNo { get; set; }
        public int? CountryId { get; set; }
        public int? stateId { get; set; }
        public int? CityId { get; set; }
    }
}
