//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KrunalDhote351Entities : DbContext
    {
        public KrunalDhote351Entities()
            : base("name=KrunalDhote351Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Student> Student { get; set; }

        public System.Data.Entity.DbSet<School.Models.Models.StudentModel> StudentModels { get; set; }

        public System.Data.Entity.DbSet<School.Models.Models.CityModel> CityModels { get; set; }

        public System.Data.Entity.DbSet<School.Models.Models.CountryModel> CountryModels { get; set; }

        public System.Data.Entity.DbSet<School.Models.Models.DepartmentModel> DepartmentModels { get; set; }

        public System.Data.Entity.DbSet<School.Models.Models.StateModel> StateModels { get; set; }
    }
}
