//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Kirtan_test_375Entities : DbContext
    {
        public Kirtan_test_375Entities()
            : base("name=Kirtan_test_375Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<CouponCodeMaster> CouponCodeMaster { get; set; }
    
        public virtual ObjectResult<sp_orderDetails_Result> sp_orderDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_orderDetails_Result>("sp_orderDetails");
        }
    }
}
