//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual user user { get; set; }
        public virtual Items Items { get; set; }
    }
}
