//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KrunalDhote351Entities : DbContext
    {
        public KrunalDhote351Entities()
            : base("name=KrunalDhote351Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    
        public virtual ObjectResult<sp_GetQuistionById_Result> sp_GetQuistionById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetQuistionById_Result>("sp_GetQuistionById", idParameter);
        }
    
        public virtual ObjectResult<sp_GetQuistion_Result> sp_GetQuistion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetQuistion_Result>("sp_GetQuistion");
        }
    }
}
