//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> WaiterId { get; set; }
        public string Menus { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<System.DateTime> OrderDates { get; set; }
    
        public virtual Users2 Users2 { get; set; }
        public virtual Users2 Users21 { get; set; }
    }
}
